"""add_financeiro_models

Revision ID: 017a51b72478
Revises: 72c3f6a57101
Create Date: 2026-07-01 09:57:49.579407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '017a51b72478'
down_revision: Union[str, Sequence[str], None] = '72c3f6a57101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_table('clientes')
    op.create_index(op.f('ix_apontamentos_produtividade_colaborador_id'), 'apontamentos_produtividade', ['colaborador_id'], unique=False)
    op.create_foreign_key(None, 'apontamentos_produtividade', 'colaboradores_produtividade', ['colaborador_id'], ['id'])
    op.create_index(op.f('ix_comercial_clientes_cidade_entrega'), 'comercial_clientes', ['cidade_entrega'], unique=False)
    op.create_index(op.f('ix_comercial_clientes_condicao_pagamento_id'), 'comercial_clientes', ['condicao_pagamento_id'], unique=False)
    op.create_index(op.f('ix_comercial_clientes_email_cobranca'), 'comercial_clientes', ['email_cobranca'], unique=False)
    op.create_index(op.f('ix_comercial_clientes_forma_pagamento_id'), 'comercial_clientes', ['forma_pagamento_id'], unique=False)
    op.create_index(op.f('ix_comercial_clientes_municipio_cobranca'), 'comercial_clientes', ['municipio_cobranca'], unique=False)
    op.create_index(op.f('ix_comercial_clientes_nome_vendedor_interno'), 'comercial_clientes', ['nome_vendedor_interno'], unique=False)
    op.create_index(op.f('ix_comercial_clientes_representante_id'), 'comercial_clientes', ['representante_id'], unique=False)
    op.create_index(op.f('ix_comercial_clientes_uf_cobranca'), 'comercial_clientes', ['uf_cobranca'], unique=False)
    op.create_index(op.f('ix_comercial_clientes_uf_entrega'), 'comercial_clientes', ['uf_entrega'], unique=False)
    op.alter_column('comercial_representantes', 'comissao_padrao',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('configuracoes_vendas', sa.Column('desconto_maximo_sem_aprovacao', sa.Float(), nullable=True))
    op.add_column('contas_financeiras', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.add_column('contas_financeiras', sa.Column('conta_bancaria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contas_financeiras', 'categorias_financeiras', ['categoria_id'], ['id'])
    op.create_foreign_key(None, 'contas_financeiras', 'contas_bancarias', ['conta_bancaria_id'], ['id'])
    op.create_unique_constraint(None, 'maquinas', ['codigo'])
    op.drop_index(op.f('ix_movimentacoes_estoque_tipo_created_at'), table_name='movimentacoes_estoque')
    op.create_foreign_key(None, 'movimentacoes_estoque', 'estoque_lotes', ['lote_id'], ['id'])
    op.create_foreign_key(None, 'pedidos_venda', 'comercial_clientes', ['cliente_id'], ['id'])
    op.create_foreign_key(None, 'pedidos_venda', 'comercial_representantes', ['representante_id'], ['id'])
    op.create_foreign_key(None, 'pedidos_venda', 'usuarios', ['vendedor_interno_id'], ['id'])
    op.create_foreign_key(None, 'pedidos_venda', 'comercial_condicoes_pagamento', ['condicao_pagamento_id'], ['id'])
    op.create_index(op.f('ix_produtos_marca'), 'produtos', ['marca'], unique=False)
    op.alter_column('setores_produtividade', 'meta_colaborador_diaria',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setores_produtividade', 'meta_colaborador_diaria',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_produtos_marca'), table_name='produtos')
    op.drop_constraint(None, 'pedidos_venda', type_='foreignkey')
    op.drop_constraint(None, 'pedidos_venda', type_='foreignkey')
    op.drop_constraint(None, 'pedidos_venda', type_='foreignkey')
    op.drop_constraint(None, 'pedidos_venda', type_='foreignkey')
    op.drop_constraint(None, 'movimentacoes_estoque', type_='foreignkey')
    op.create_index(op.f('ix_movimentacoes_estoque_tipo_created_at'), 'movimentacoes_estoque', ['tipo', 'created_at'], unique=False)
    op.drop_constraint(None, 'maquinas', type_='unique')
    op.drop_constraint(None, 'contas_financeiras', type_='foreignkey')
    op.drop_constraint(None, 'contas_financeiras', type_='foreignkey')
    op.drop_column('contas_financeiras', 'conta_bancaria_id')
    op.drop_column('contas_financeiras', 'categoria_id')
    op.drop_column('configuracoes_vendas', 'desconto_maximo_sem_aprovacao')
    op.alter_column('comercial_representantes', 'comissao_padrao',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_comercial_clientes_uf_entrega'), table_name='comercial_clientes')
    op.drop_index(op.f('ix_comercial_clientes_uf_cobranca'), table_name='comercial_clientes')
    op.drop_index(op.f('ix_comercial_clientes_representante_id'), table_name='comercial_clientes')
    op.drop_index(op.f('ix_comercial_clientes_nome_vendedor_interno'), table_name='comercial_clientes')
    op.drop_index(op.f('ix_comercial_clientes_municipio_cobranca'), table_name='comercial_clientes')
    op.drop_index(op.f('ix_comercial_clientes_forma_pagamento_id'), table_name='comercial_clientes')
    op.drop_index(op.f('ix_comercial_clientes_email_cobranca'), table_name='comercial_clientes')
    op.drop_index(op.f('ix_comercial_clientes_condicao_pagamento_id'), table_name='comercial_clientes')
    op.drop_index(op.f('ix_comercial_clientes_cidade_entrega'), table_name='comercial_clientes')
    op.drop_constraint(None, 'apontamentos_produtividade', type_='foreignkey')
    op.drop_index(op.f('ix_apontamentos_produtividade_colaborador_id'), table_name='apontamentos_produtividade')
    op.create_table('clientes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cpf_cnpj', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cidade', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('clientes_pkey'))
    )
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=True)
    # ### end Alembic commands ###
