"""Add gerar_nota to pedidos_venda

Revision ID: 64b48c234fbc
Revises: e849d971ab29
Create Date: 2026-07-17 13:40:24.119198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b48c234fbc'
down_revision: Union[str, Sequence[str], None] = 'e849d971ab29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comercial_clientes', 'comercial_representantes', ['vendedor_padrao_id'], ['id'])
    op.drop_index(op.f('ix_movimentacoes_estoque_tipo_created_at'), table_name='movimentacoes_estoque')
    op.alter_column('notas_fiscais', 'obs',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('notas_fiscais', 'valor_total')
    op.add_column('pedidos_venda', sa.Column('gerar_nota', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'pedidos_venda', 'comercial_representantes', ['vendedor_id'], ['id'])
    op.alter_column('usuarios', 'comissao_percentual',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'comissao_percentual',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'pedidos_venda', type_='foreignkey')
    op.drop_column('pedidos_venda', 'gerar_nota')
    op.add_column('notas_fiscais', sa.Column('valor_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('notas_fiscais', 'obs',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_movimentacoes_estoque_tipo_created_at'), 'movimentacoes_estoque', ['tipo', 'created_at'], unique=False)
    op.drop_constraint(None, 'comercial_clientes', type_='foreignkey')
    # ### end Alembic commands ###
