"""Add campos_json and zpl_base to EtiquetaTemplate

Revision ID: 72c3f6a57101
Revises: 9392e205035e
Create Date: 2026-04-28 10:45:57.203250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c3f6a57101'
down_revision: Union[str, Sequence[str], None] = '9392e205035e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etiqueta_templates', sa.Column('campos_json', sa.Text(), nullable=True))
    op.add_column('etiqueta_templates', sa.Column('zpl_base', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etiqueta_templates', 'zpl_base')
    op.drop_column('etiqueta_templates', 'campos_json')
    # ### end Alembic commands ###
