"""Add missing fields to clientes

Revision ID: ccd88aa1d3ea
Revises: dae690883ada
Create Date: 2026-07-13 15:31:42.677349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd88aa1d3ea'
down_revision: Union[str, Sequence[str], None] = 'dae690883ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comercial_clientes', sa.Column('codigo_externo', sa.String(), nullable=True))
    op.add_column('comercial_clientes', sa.Column('contribuinte', sa.String(), nullable=True))
    op.add_column('comercial_clientes', sa.Column('inscricao_municipal', sa.String(), nullable=True))
    op.add_column('comercial_clientes', sa.Column('codigo_regime_tributario', sa.String(), nullable=True))
    op.add_column('comercial_clientes', sa.Column('inscricao_suframa', sa.String(), nullable=True))
    op.add_column('comercial_clientes', sa.Column('data_nascimento', sa.DateTime(), nullable=True))
    op.add_column('comercial_clientes', sa.Column('status_crm', sa.String(), nullable=True))
    op.add_column('comercial_clientes', sa.Column('vendedor_id', sa.String(), nullable=True))
    op.add_column('comercial_clientes', sa.Column('limite_credito', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comercial_clientes', 'limite_credito')
    op.drop_column('comercial_clientes', 'vendedor_id')
    op.drop_column('comercial_clientes', 'status_crm')
    op.drop_column('comercial_clientes', 'data_nascimento')
    op.drop_column('comercial_clientes', 'inscricao_suframa')
    op.drop_column('comercial_clientes', 'codigo_regime_tributario')
    op.drop_column('comercial_clientes', 'inscricao_municipal')
    op.drop_column('comercial_clientes', 'contribuinte')
    op.drop_column('comercial_clientes', 'codigo_externo')
    # ### end Alembic commands ###
