"""Add tipo_contato to clientes

Revision ID: dae690883ada
Revises: 017a51b72478
Create Date: 2026-07-13 15:18:29.854306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae690883ada'
down_revision: Union[str, Sequence[str], None] = '017a51b72478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comercial_clientes', sa.Column('tipo_contato', sa.String(), nullable=False, server_default='Cliente'))
    op.add_column('contas_financeiras', sa.Column('recorrencia_id', sa.String(), nullable=True))
    op.add_column('contas_financeiras', sa.Column('parcela_atual', sa.Integer(), nullable=True))
    op.add_column('contas_financeiras', sa.Column('total_parcelas', sa.Integer(), nullable=True))
    op.add_column('contas_financeiras', sa.Column('tags_csv', sa.String(), nullable=True))
    op.create_index(op.f('ix_contas_financeiras_recorrencia_id'), 'contas_financeiras', ['recorrencia_id'], unique=False)
    op.drop_index(op.f('ix_movimentacoes_estoque_tipo_created_at'), table_name='movimentacoes_estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movimentacoes_estoque_tipo_created_at'), 'movimentacoes_estoque', ['tipo', 'created_at'], unique=False)
    op.drop_index(op.f('ix_contas_financeiras_recorrencia_id'), table_name='contas_financeiras')
    op.drop_column('contas_financeiras', 'tags_csv')
    op.drop_column('contas_financeiras', 'total_parcelas')
    op.drop_column('contas_financeiras', 'parcela_atual')
    op.drop_column('contas_financeiras', 'recorrencia_id')
    op.drop_column('comercial_clientes', 'tipo_contato')
    # ### end Alembic commands ###
