"""Add new fields to representantes

Revision ID: e849d971ab29
Revises: ccd88aa1d3ea
Create Date: 2026-07-14 08:46:56.581953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e849d971ab29'
down_revision: Union[str, Sequence[str], None] = 'ccd88aa1d3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comercial_representantes', sa.Column('fantasia', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('tipo_pessoa', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('cpf_cnpj', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('contribuinte', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('inscricao_estadual', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('cep', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('cidade', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('uf', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('endereco', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('bairro', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('numero', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('complemento', sa.String(), nullable=True))
    op.add_column('comercial_representantes', sa.Column('celular', sa.String(), nullable=True))
    op.alter_column('comercial_representantes', 'codigo',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('ix_comercial_representantes_codigo'), table_name='comercial_representantes')
    op.create_index(op.f('ix_comercial_representantes_codigo'), 'comercial_representantes', ['codigo'], unique=False)
    op.drop_index(op.f('ix_movimentacoes_estoque_tipo_created_at'), table_name='movimentacoes_estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movimentacoes_estoque_tipo_created_at'), 'movimentacoes_estoque', ['tipo', 'created_at'], unique=False)
    op.drop_index(op.f('ix_comercial_representantes_codigo'), table_name='comercial_representantes')
    op.create_index(op.f('ix_comercial_representantes_codigo'), 'comercial_representantes', ['codigo'], unique=True)
    op.alter_column('comercial_representantes', 'codigo',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('comercial_representantes', 'celular')
    op.drop_column('comercial_representantes', 'complemento')
    op.drop_column('comercial_representantes', 'numero')
    op.drop_column('comercial_representantes', 'bairro')
    op.drop_column('comercial_representantes', 'endereco')
    op.drop_column('comercial_representantes', 'uf')
    op.drop_column('comercial_representantes', 'cidade')
    op.drop_column('comercial_representantes', 'cep')
    op.drop_column('comercial_representantes', 'inscricao_estadual')
    op.drop_column('comercial_representantes', 'contribuinte')
    op.drop_column('comercial_representantes', 'cpf_cnpj')
    op.drop_column('comercial_representantes', 'tipo_pessoa')
    op.drop_column('comercial_representantes', 'fantasia')
    # ### end Alembic commands ###
